dist: trusty

language: cpp

services:
  - docker

addons:
  apt:
    packages:
      - libpcap-dev
      - libssl-dev

branches:
  only:
  - master
  - /release\/.*/

notifications:
  email:
    recipients:
    - zeek-commits-internal@zeek.org

# Build Zeek and run tests in the following Linux distros (specifying "travis"
# builds Zeek in Travis without using docker).
env:
  - distro: centos_7
  - distro: debian_9
  - distro: fedora_30
  - distro: ubuntu_16.04
  - distro: ubuntu_18.04
  - distro: ubuntu_18.04_leaktest

install: sh testing/scripts/travis-job install $distro

before_script: sh testing/scripts/travis-job build $distro

script: sh testing/scripts/travis-job run $distro
