name: Check and publish Docker images

on:
  pull_request:
  push:
    branches: [master]
    tags:
      - 'v*'
      - '!v*-dev'
      - 'release'

defaults:
  run:
    shell: bash


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_TAG: zeek:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      # Create and boot a loader. This will e.g., provide caching
      # so we avoid rebuilds of the same image after this step.
      - uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: docker/Dockerfile
          # Load and tag the image so it can be used by the test job below.
          load: true
          tags: ${{ env.TEST_TAG }}

      # Run tests on the just created image.
      - name: Run tests
        uses: plexsystems/container-structure-test-action@v0.2.0
        with:
            image: ${{ env.TEST_TAG }}
            config: docker/container-structure-test.yaml

      - name: Get Version
        id: version
        run: echo "::set-output name=RELEASE_VERSION::$(cat VERSION)"
      - name: Compute target tag
        id: target
        env:
          RELEASE_VERSION: ${{ steps.version.outputs.RELEASE_VERSION }}
        run: |
          # Translate the Github reference into a tag name.
          #
          # - `release` tag maps to `zeek:latest`
          # - `v*` tag (excluding `v*-dev` tags) maps to `zeek:RELEASE_VERSION`
          # - `master` branch maps to `zeek-dev:latest`
          #
          # Any other refs are not published below.
          if [ "${GITHUB_REF}" = "refs/tags/release" ]; then
            echo "::set-output name=tag::zeek:latest"
          elif [ "${GITHUB_REF}" = "refs/heads/master" ]; then
            echo "::set-output name=tag::zeek-dev:latest"
          elif [[ "${GITHUB_REF}" = refs/heads/v* ]] && [[ "${GITHUB_REF}" != refs/heads/v*-dev ]]; then
            echo "::set-output name=tag::zeek:${RELEASE_VERSION}"
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v1
        # Secrets for the login are not available for pull requests.
        if: github.event_name == 'push'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push
        # Only publish if we did compute a tag.
        if: github.event_name == 'push' && steps.target.outputs.tag != ''
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: docker/Dockerfile
          push: true
          tags: |
            zeekurity/${{ steps.target.outputs.tag}}
