name: Generate Documentation

on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

defaults:
  run:
    shell: bash

jobs:
  generate:
    if: github.repository == 'zeek/zeek'
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Switch doc submodule to master
        run: cd doc && git checkout master

      - name: Fetch Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            git \
            cmake \
            make \
            gcc \
            g++ \
            flex \
            bison \
            libpcap-dev \
            libssl-dev \
            python3 \
            python3-dev \
            python3-pip\
            swig \
            zlib1g-dev \
            libkrb5-dev \
            bsdmainutils \
            sqlite3
          # Many distros adhere to PEP 394's recommendation for `python` =
          # `python2` so this is a simple workaround until we drop Python 2
          # support and explicitly use `python3` for all invocations.
          sudo ln -sf /usr/bin/python3 /usr/local/bin/python
          sudo pip3 install -r doc/requirements.txt

      - name: Configure
        run: ./configure

      - name: Build
        run: cd build && make -j $(nproc)

      - name: Generate Docs
        run: |
          git config --global user.name zeek-bot
          git config --global user.email info@zeek.org

          echo "*** Generating Zeekygen Docs ***"
          ./ci/update-zeekygen-docs.sh || exit 1

          echo "*** Generating Sphinx Docs ***"
          cd doc
          make > make.out 2>&1
          make_status=$?
          echo "*** Sphinx Build Output ***"
          cat make.out
          test ${make_status} -ne 0 && exit 1
          echo "*** Check for Sphinx Warnings ***"
          grep -q WARNING make.out && exit 1
          rm make.out

      - name: Push zeek-docs Changes
        if: github.event_name == 'schedule'
        run: |
          cd doc
          git remote set-url origin "https://zeek-bot:${{ secrets.ZEEK_BOT_TOKEN }}@github.com/zeek/zeek-docs"
          git add scripts/ script-reference/
          git status
          git commit -m "Generate docs" && git push || /bin/true

      - name: Update zeek-docs Submodule
        if: github.event_name == 'schedule'
        run: |
          git config --global user.name zeek-bot
          git config --global user.email info@zeek.org
          git remote add auth "https://zeek-bot:${{ secrets.ZEEK_BOT_TOKEN }}@github.com/zeek/zeek"
          git add doc
          git status
          git commit -m 'Update doc submodule [nomail] [skip ci]' && git push auth master || /bin/true

      - name: Send email
        if: failure()
        uses: dawidd6/action-send-mail@v3.4.1
        with:
          server_address: ${{secrets.SMTP_HOST}}
          server_port: ${{secrets.SMTP_PORT}}
          username: ${{secrets.SMTP_USER}}
          password: ${{secrets.SMTP_PASS}}
          subject: generate-docs Github Action failed!
          body: generate-docs job of ${{github.repository}} Failed! See https://github.com/${{github.repository}}/actions/runs/${{github.run_id}} for details.
          to: ${{secrets.MAIL_TO}}
          from: Github Actions <${{secrets.MAIL_FROM}}>
